version: "3.0"

volumes:
  postgres-data:

services:

  db:
    image: postgres:latest
    container_name: grest-example-jackc_pgx-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
      driver: none

  app:
    image: golang:latest
    container_name: grest-example-jackc_pgx
    environment:
      DB_HOST: 'db:5432'
      DB_BASE: 'test'
      DB_USER: 'user'
      DB_PASS: 'pass'
      HTTP_PORT: '8080'
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: bash -c "go test -v . && go run main.go"
    depends_on:
      - db
