language: go

go:
  - 1.13.x
  - master

os:
  - linux
  - osx

services:
  - postgresql

addons:
  postgresql: '10'

env:
  - GO111MODULE=on DB_PORT=5432 DB_USER=user DB_PASS=pass DB_BASE=test

install:
  - go mod download

before_script:
  - psql -c "CREATE DATABASE IF NOT EXISTS test;" -U postgres
  - psql -c "CREATE USER IF NOT EXISTS user WITH PASSWORD 'pass';" -U postgres

script:
  - go test -v ./internal/dbase
  - go test -v ./internal/helper
  - go test -v ./internal/logger
  - go test -v ./internal/mux
  - go test -v ./usr
  - go test -v ./db
  - go test -v ./example/driver/database-sql
  - go test -v ./example/driver/jackc-pgx
  - go test -v .
  - go build -ldflags "-s -w" -o "psql-rest" ./example/main.go