language: go

services:
  - postgresql

env:
  - GO111MODULE=on PGPORT=5432 PGUSER=user PGPASSWORD=pass PGDATABASE=test

install:
  - go mod download

script:
  - go test -v .
  - go build -ldflags "-s -w" -o "psql-rest" ./example/main.go