language: go

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - master

os:
  - linux
  - osx

services:
  - postgresql

addons:
  postgresql: '10'

env:
  global:
    - GO111MODULE=on DB_PORT=5432 DB_USER=tester DB_PASS=pass DB_BASE=test

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      export PG_DATA=$(brew --prefix)/var/postgres
      pg_ctl -w start -l postgres.log --pgdata ${PG_DATA}
      createuser -s postgres
    fi
  - go mod download

before_script:
  - psql -c "CREATE DATABASE test;" -U postgres
  - psql -c "CREATE USER tester WITH PASSWORD 'password';" -U postgres

script:
  - go test -v ./internal/dbase
  - go test -v ./internal/helper
  - go test -v ./internal/logger
  - go test -v ./internal/mux
  - go test -v ./usr
  - go test -v ./db
  - cd example/jackc-pgx/
  - go test -v .
  - go build -ldflags "-s -w" -o "jackc-pgx" main.go
  - cd ../database-sql
  - go test -v .
  - go build -ldflags "-s -w" -o "database-sql" main.go
  - cd ../..
  - go test -v .